title: Hello! I'm skyhuihui
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/skyhuihui.github.io"
url: "http://skyhuihui.top"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: skyhuihui # add your name
author-img:  # add your photo
about-author: 我是一个区块链开发人员，热爱，持续学习，并且前进 # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: skyhuihui 
social-linkedin: # add your Linkedin handle
social-email: huihuisky@outlook.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
